# Generated by Django 6.0.1 on 2026-01-15 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('videoID', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('videoURL', models.URLField(max_length=500, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Words',
            fields=[
                ('wordID', models.AutoField(primary_key=True, serialize=False)),
                ('word', models.CharField(db_index=True, max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sentences',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sentence', models.CharField(max_length=2064)),
                ('start', models.FloatField()),
                ('duration', models.FloatField()),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indexer.videos')),
            ],
        ),
        migrations.CreateModel(
            name='Indexing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posetion', models.IntegerField()),
                ('sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indexer.sentences')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indexer.words')),
            ],
            options={
                'unique_together': {('word', 'sentence', 'posetion')},
            },
        ),
    ]
