# Generated by Django 6.0.1 on 2026-01-15 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('videoID', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('videoURL', models.URLField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Words',
            fields=[
                ('wordID', models.AutoField(primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=255)),
                ('cnt', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Indexing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.FloatField()),
                ('end', models.FloatField()),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indexer.videos')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indexer.words')),
            ],
            options={
                'unique_together': {('word', 'video', 'start', 'end')},
            },
        ),
    ]
