# Generated by Django 6.0.1 on 2026-01-15 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='words',
            name='cnt',
            field=models.IntegerField(default=1),
        ),
    ]
