# Generated by Django 6.0.1 on 2026-01-16 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexer', '0002_words_cnt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indexing',
            options={'ordering': ['word_id', 'sentence_id']},
        ),
    ]
